Add calendar extension layer
brefphp/extra-php-extensions pull request #206
Opened 2021-03-27 18:17 UTC by semsphy

Add calendar extension.

2021-03-27 18:34 UTC, GrahamCampbell requested changes

2021-03-27 18:34 UTC, GrahamCampbell commented on Readme.md
> +| Calendar          | `${bref:extra.calendar-php-74}`      |
missing spaces ;)

2021-03-28 01:51 UTC, semsphy commented on Readme.md
> +| Calendar          | `${bref:extra.calendar-php-74}`      |
Nice catch :)

2021-03-28 02:06 UTC, GrahamCampbell requested changes

2021-03-28 02:06 UTC, GrahamCampbell commented on Readme.md
> +| Calendar          | `${bref:extra.calendar-php-74}`        |
Alignment still incorrect.

2021-03-28 02:08 UTC, semsphy commented on Readme.md
> +| Calendar          | `${bref:extra.calendar-php-74}`        |
:( thank.

2021-03-29 03:09 UTC, semsphy commented
@Nyholm, any chance to review my PR, pls.

2021-03-29 07:07 UTC, Nyholm commented on layers/calendar/config.json
> +        "80",
This is not valid json. 

```suggestion
        "80"
```

2021-03-29 07:14 UTC, Nyholm approved these changes
Thank you

2021-03-29 07:15 UTC, merged