Release 0.11.22
brefphp/extra-php-extensions pull request #308
Opened 2022-01-12 20:10 UTC by Nyholm

2022-01-12 21:30 UTC, GrahamCampbell requested changes

2022-01-12 21:30 UTC, GrahamCampbell commented on CHANGELOG.md
> +- Kafka extension update dto 1.8.2
typo ;)

2022-01-31 17:28 UTC, mnapoli commented
Build fixed in the `prepare-release` branch, and I'm sorry I ended up updating the release to include #311 (since 0.11.22 was never built or release it seems like it shouldn't have bad side effects).

2022-02-01 03:00 UTC, Nyholm commented
Great. Thank you for fixing this build. 

I just squash and merge =)

2022-02-01 03:03 UTC, Nyholm commented on CHANGELOG.md
> +- Kafka extension update dto 1.8.2
Thank you

2022-02-01 04:05 UTC, merged

2022-02-01 10:26 UTC, mnapoli commented
Thank you!